### ISSUE TITLE
Investigate new hand workflow

### ISSUE THREAD

**Issue by MattReimer** [Riverscapes/riverscapes-tools#131]
### TODO's

* [x] Get [TauDEM installed and working on windows](https://hydrology.usu.edu/taudem/taudem5/downloads.html). this should be easier than on linux because you shouldn't need to compile anything
* [x] Run HAND for all the HUCS listed in #111 to prove that you can get it working
    - 16010202 - Middle Bear
    - 10190002 - Upper South Platte
    - 10190003 - Incomplete
    - 10190004 - Clear
    - 10190005 - St. Vrain
    - 10190010 - Incomplete
* [x] I wasn't able to get hucs 10190003 or 10190010 to complete. The TAUDem tool failed with a weird segfault error. I didn't investigate. Either of these results are valuable to know:
    * You do get the errors and you can investigate a possible cause or 
    * You don't get the errors and then it's a Windows vs. Linux thing. 
 
-------------

The process for generating new hand is:

1. **pitremove** on dem.tif to give us pitfill
2. **dinfflowdir** to give us dinfflowdir_ang and dinfflowdir_slp
3. **gdal_rasterize** on NHDFlowline to give us a really basic rasterized stream
4. **dinfdistdown** to give the final HAND output

In linux bash script this looks something like this:

```bash
#!/bin/bash

pitremove \
  -z /shared/rs_context/17060304/topography/dem.tif \
  -fel /shared/taudem/17060304/pitfill.tif

dinfflowdir \
  -fel /shared/taudem/17060304/pitfill.tif \
  -ang /shared/taudem/17060304/dinfflowdir_ang.tif \
  -slp /shared/taudem/17060304/dinfflowdir_slp.tif

gdal_rasterize \
    -te -115.9844729762425573 45.9342659162008431 -115.5958355164291333 46.2481900834219459 \
    -ts 4197 3390 \
    -burn 1 \
    /shared/rs_context/17060304/hydrology/NHDFlowline.shp \
    /shared/taudem/17060304/rasterized_flowline.tif

dinfdistdown \
  -ang /shared/taudem/17060304/dinfflowdir_ang.tif \
  -fel /shared/taudem/17060304/pitfill.tif \
  -src /shared/taudem/17060304/rasterized_flowline.tif \
  -dd /shared/taudem/17060304/hand.tif
  -m v

echo "DONE"
```

----------
### Related Issues:

* #98 Our original discussion about HAND
* #111 The result of my hand investigations

----------

**Comment by philipbaileynar** [comment]
@KellyMWhitehead some of Matt's attempts failed with no error message. We are wondering if this might be caused by the rasters being in geographic coordinates which might complicate the math with very small distances in degrees. Just something to explore if things start to break for you...

**Comment by KellyMWhitehead** [comment]
I was able to run the hand process successfully on my windows machine for all visits i tested, including the two that previously failed. I installed taudem using the windows installer, and I believe it installed gdal 2.1 over my existing 2.2 version.  

Note I also needed to change the last argument in the last tool from `-m` v to `-m ave v`

**Comment by MattReimer** [comment]
This is great and super valuable to know. Thanks @KellyMWhitehead 

Some conclusions I take away from this:

1. TauDEM works *(yay!)*
2. Our data is fine the way it is. _(double-plus yay!)_ 
3. There's a small chance that changing `-m v` to `-m ave v` will fix the issues but I'm not getting my hopes up on that one.
4. There's a much greater chance that the problem is with the compiled linux version of TauDEM in which case I'll need to try to recompile it with an older version of GDAL. 

Try (3) first but assume (4) is the fix.

**Comment by philipbaileynar** [comment]
Reassigning to Matt to get TauDEM working on AWS. Kelly's research is complete.

**Comment by philipbaileynar** [comment]
During the call I just had with the USGS I was told that the latest HAND algorithm is available from CAHABA. I even see mention of a docker box. @MattReimer this might be huge!!!!!

https://github.com/NOAA-OWP/cahaba

**Comment by joewheaton** [comment]
I would love to know and learn more about the CAHABA model. That could be really useful if we better understand it.

Also, I just noticed on their documenation the [USACE National Levee Database](https://levees.sec.usace.army.mil/), which could be really, really helpful for our flooplain connectiivty. I know it is incomplete, but it still has 25,000 miles of levees, so we might as well have it where we can have it. 

USACE National Levee Database: -Access here: https://levees.sec.usace.army.mil/ - -
![image](https://user-images.githubusercontent.com/9723905/104665841-a5636a00-568f-11eb-824e-2d0080afc56c.png)

What's more, when you drill in, it has the polyline features and "what is protected" and what is it worth?
![image](https://user-images.githubusercontent.com/9723905/104665923-cc21a080-568f-11eb-9061-388363e74a68.png)

**Comment by MattReimer** [comment]
I can't comment on the method but it seems that they are also compiling TauDEM on an Ubuntu box

https://github.com/NOAA-OWP/cahaba/blob/dev/Dockerfile.dev#L15-L16

Maybe I can learn something from the compile flags but the tools at least are not different from what we were doing

**Comment by MattReimer** [comment]
Unfortunately, using their Docker box it seems like taudem still fails unexpectedly.

```
root@a37530983552:/shared/taudem# /dependencies/taudem/bin/pitremove -z /shared/rs_context/10190003/topography/dem.tif -fel /shared/taudem/10190003/pitfill.tif
PitRemove version 5.3.9
Input file /shared/rs_context/10190003/topography/dem.tif has geographic coordinate system.
Nodata value input to create partition from file: -340282339999999992395853996843190976512.000000
Nodata value recast to float used in partition raster: -340282346638528859811704183484516925440.000000
This run may take on the order of 8 minutes to complete.
This estimate is very approximate. 
Run time is highly uncertain as it depends on the complexity of the input data 
and speed and memory of the computer. This estimate is based on our testing on 
a dual quad core Dell Xeon E5405 2.0GHz PC with 16GB RAM.
Killed
```

This is a preliminary finding so we probably need to delve. Into their steps to see if we're doing things in the wrong order. It is disappointing though that we are getting such poor errors.

**Comment by MattReimer** [comment]
A little more investigation:

This `killed` error indicates a resource shortage.  Incresing the RAM seems to solve it.

This issue is fixed. Let's open up a new one to implement the new HAND using python
