### ISSUE TITLE
Fill in VBET parameterization spreadsheet

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#310]
@joewheaton and @shelbysawyer please populate the VBET parameterization spreadsheet:

https://docs.google.com/spreadsheets/d/1rClE5BCK8nBXZBwH7cRRa3MJseE1Vj5xhYutxeHNotE/edit?usp=sharing

## Tasks
------------
## Slope Parameterization

- [x] Specify Slope Transform Curve for Small
- [x] Specify Slope Transform Curve for Medium
- [x] Specify Slope Transform Curve for Large

## HAND Parameterization
- [x] Specify HAND Transform Curve for Small
- [x] Specify HAND Transform Curve for Medium
- [x] Specify HAND Transform Curve for Large

## Distance from Channel
- [x] Specify Dist Transform Curve for Small
- [x] Specify Dist Transform Curve for Medium
- [x] Specify Dist Transform Curve for Large

## TWI
- [x] Specify TWI Transform Curve for Small
- [x] Specify TWI Transform Curve for Medium
- [x] Specify TWI Transform Curve for Large

**Comment by joewheaton** [comment]
We've been adding in validation points to vbet_parameterization in PostGIS Brat_Database. Discussed plan of attack for next week while @KellyMWhitehead fixes channels (#320) and @lauren-herbine and @shelbysawyer get some points in as well. Hope to address by next Friday.

**Comment by shelbysawyer** [comment]
@joewheaton @philipbaileynar Is this a good place to re-list the HUCs that @lauren-herbine and I dropped points in?

**Comment by lauren-herbine** [comment]
Outside of the Bear River/Logan area and some MHFD, and a few other "random" HUCs we have already dropped points in, @shelbysawyer and I will be focusing on these HUCs (the ones I chose for RS validation) to round out the point count:

05020004 (Cheat, WV) @lauren-herbine 
07050002 (Flambeau, WI) @lauren-herbine 
08080102 (Bayou Teche, LA) @lauren-herbine 
10080010 (Big Horn, MT/WY) @shelbysawyer (and @lauren-herbine b/c I've started here)
10140102 (Lower Bad, SD) @shelbysawyer 
10030201 (Two Medicine, MT) @shelbysawyer

![image](https://user-images.githubusercontent.com/73319684/124187708-72fdcb80-da7b-11eb-82b3-624cc8f4c1e9.png)

**Comment by philipbaileynar** [comment]
Great @lauren-herbine. Can you remind me if these are the same hucs we already ran roverscapes context for the Mississippi?

**Comment by lauren-herbine** [comment]
@philipbaileynar Yes they are! Which is why it's easier since we already have the RS context files for them. Joe just wanted me to give you all a heads up on where VBET will likely have to be run after we're done

**Comment by joewheaton** [comment]
We got 2790 in there as of 7/6/21. This is ready for @KellyMWhitehead to extract from. We put #329 for issues that arose.

**Comment by joewheaton** [comment]
Forgot... this is the parameterization of the transform functions... So we're not done yet.

**Comment by joewheaton** [comment]
@philipbaileynar do you to add Distance From Drainage Cell (x 3 for drainage area) and TWI (just one)?

**Comment by philipbaileynar** [comment]
Add whatever you need to get the job done. 

Kelly is going to extract two values.

**Comment by joewheaton** [comment]
What do you mean he is extracting two values? Isn't he extracting values for every single line of evidence? 
- Slope
- HAND
- Distance from Drainage
- TWI

**Comment by philipbaileynar** [comment]
typo... I meant TWI (was on my phone)

**Comment by KellyMWhitehead** [comment]
[Here](https://drive.google.com/file/d/1Lzt6vCvEwRjBrXzrUkTkghX5mg-rc6pk/view?usp=sharing) is the csv with extracted vbet evidence values. There are a three watersheds that HAND was unable to be generated - we are working on getting this fixed. Otherwise let me know if there are questions or concerns.

**Comment by shelbysawyer** [comment]
Thanks @KellyMWhitehead!

@joewheaton My latest R script can be found [here](https://github.com/shelbysawyer/vbet_validation). Still working on that last part of breaking things out by user, but it's almost there.

**Comment by joewheaton** [comment]
> [Here](https://drive.google.com/file/d/1Lzt6vCvEwRjBrXzrUkTkghX5mg-rc6pk/view?usp=sharing) is the csv with extracted vbet evidence values. There are a three watersheds that HAND was unable to be generated - we are working on getting this fixed. Otherwise let me know if there are questions or concerns.

Thanks @KellyMWhitehead. A few questions:
1. Do you have the look up table for what CategoryID corresponds to what?
2. Why didn't the UserID come through (or for that matter date fields)? We sort of need those.

**Comment by joewheaton** [comment]
> Thanks @KellyMWhitehead!
> 
> @joewheaton My latest R script can be found [here](https://github.com/shelbysawyer/vbet_validation). Still working on that last part of breaking things out by user, but it's almost there.

Excellent @shelbysawyer. It looks like you got pretty far. The sort by user is all for not until we get that field fixed.... (also less important at this stage). @philipbaileynar and @KellyMWhitehead did you guys try the R script?

**Comment by philipbaileynar** [comment]
I have not tried the r script. Relying on you fine folks for that.

**Comment by KellyMWhitehead** [comment]
@joewheaton , @shelbysawyer 

Here is a new version of the csv with the category name added. For reference, the lookup table can also be found in the postgis database (vbetcategories). I also included the other fields that were missing.

[vbet_evidence_02.csv](https://github.com/Riverscapes/riverscapes-tools/files/6826194/vbet_evidence_02.csv)
[categorylookup.csv](https://github.com/Riverscapes/riverscapes-tools/files/6826202/categorylookup.csv)

**Comment by lauren-herbine** [comment]
@shelbysawyer (I know you're in the middle of the Grand right now, just dropping a note for when you're back)- I was able to get pieces of your script to work correctly. The main issues are/were:

- some basic capitalization/spelling/naming issues that I've corrected
- creating the "evidence" table. I'm not sure why this didn't work, but I could not get the csv to load into this. It worked for the "observations" table, so I ran your box plots and histograms on that.
- changing the data type of userid to factor. it didn't like that. not sure why, but also not sure what/why you need to do that so I didn't mess around with it. just skipped it in my script.
- When I changed from using the "evidence" table to the "observations" table, I had to change some of the spelling/capitalization for the column names since apparently they are different between the two (i.e. in "evidence" it is "twi" while in "observations" it is "TWI")
- obviously changed everything to "vbet_evidence_02.csv"
- There were a decent amount of pieces that ran, but came with this warning:
`Warning message:
Removed 446 rows containing non-finite values (stat_bin).`

Looks like it is really close! Only spent a half hour or so on it, so I'm sure it'll come together pretty quickly when you're back. Some first-go graphs for you from your script:
![image](https://user-images.githubusercontent.com/73319684/125860716-a2bacc5d-6c90-4f30-b36b-3f8fdd57c853.png)
![image](https://user-images.githubusercontent.com/73319684/125860776-d018c208-582a-4f56-ba0f-373490603507.png)
![image](https://user-images.githubusercontent.com/73319684/125861146-7ccb17a6-076b-47ea-bd3f-14eced64cc4a.png)

I didn't mess with anything from the `# Still in progress of converting these over to new column names` part or the `# Summary statistics` part, but you can find my edits on [this fork](https://github.com/lauren-herbine/vbet_validation/blob/main/vbet_validation.R).

**Comment by shelbysawyer** [comment]
@KellyMWhitehead I'm working with the updated csv that you provided above and I'm not seeing the associated drainage area information. Can you please send another csv my way that includes that information?

**Comment by joewheaton** [comment]
@shelbysawyer I just checked in with @philipbaileynar who was pinging with @KellyMWhitehead. He is re-running right now to get those drainage size categories, and it should come by end of day.  He's going to give you drainage area (sq. km), stream order and input zones.

Yes it will be small, medium and high. Currently, the "inputZones" are:

- 0 (Low): Stream Order 0, 1 & 2
- 1 (Med): Stream Order 3 & 4
- 2 (High): Stream Order 5 and up

We need to look at what NHD+HR defines those as Stream Order ( ) Based on modification of Strahler (p 39

**Comment by philipbaileynar** [comment]
Here's the [NHD Plus HR documentation](https://github.com/Riverscapes/riverscapes-tools/files/6864897/ofr20191096.pdf) on stream order. Page 39.

<img width="469" alt="Screen Shot 2021-07-22 at 12 53 22 PM" src="https://user-images.githubusercontent.com/8645379/126701328-915d38d8-ed66-4706-a464-89951cadc66a.png">

**Comment by KellyMWhitehead** [comment]
@shelbysawyer New version of evidence csv: [vbet_evidence_03.csv](https://github.com/Riverscapes/riverscapes-tools/files/6865685/vbet_evidence_03.csv)

Now includes:
* NHD Stream Order
* NHD Total Drainage Area for reach catchment (sqkm)
* Input Zone (based on stream order Low (0,1), Medium (2,3) and Large (4 and greater). This can be modified, but this is what vbet is currently using.

**Comment by shelbysawyer** [comment]
Thank you @KellyMWhitehead!

**Comment by joewheaton** [comment]
## Decide what we want Likelihoods to Mean
Lets use this for specifying our break points on y-axis (assuming lines of evidence will be combined by averaging values for each from 0 to 1):

| CategoryID | Likelihood | Label in Legend | Notes/Rationale |
|---|---|---|---|
|NA | 1.0 | Definitely Valley Bottom | Mythical Upper limit to be used (i.e. 100% probability). | 
| 1 | 1.0 to 0.99 | Estimated Active Channel | Mapped as and what we assign from Distance = 0 of Channel Area|
| 2 | 0.99 to 0.95 | Highly Likely Active Floodplain | |
| 3 | 0.95 to 0.90 | Likely Active Floodplain | |
| 4 | 0.90 to 0.80 | Possible Active Floodplain | |
|  NA | 0.80 | Reference point at transition between Active and Inactive floodplain |
| 5 | 0.80 to 0.68 | Possible Inactive Floodplain | |
| 6 | 0.68 | Plausible Valley Bottom Extent Active Floodplain | Let this be  |
| 8 | 0.68 to 0.45 | Very Unlikely Valley Bottom Extent | Transition to Upland (non-valley bottom) can include colluvial fans, terraces, moraines, etc. |
| 9 | 0.50 | Terrace (what it was called in spreadsheet)  | This is just a rough reference value for where terraces would fall |
| 10 | 0.45 to 0.01 | Upland | |
| NA | 0 | Definitely Not Valley Bottom | Can be known from field, but not typically arrived at?|

## Workflow for Going from Distributions & Stats to Transform Cuves
1. Decide Min Value
2. Decide Max Value (should represent upper plausible limit produced for these lines of evidence)
3. Put Note for how to handle outliers (i.e. > max or < min; noData, null values)
4. Decide if upper break point is absolute (e.g. 1) or just less (e.g. 0.995)
5. Decide if lower break point is absolute (e.g. 0) or just above (e.g. 0.01)
6. Decide shape (high bench, decrease, low bench OR low bench, increase, high bench)
7. How to choose x vertext on transition benches

**Comment by joewheaton** [comment]
Okay @KellyMWhitehead and @philipbaileynar. @shelbysawyer and I are done with first pass on [spreadsheet](https://docs.google.com/spreadsheets/d/1rClE5BCK8nBXZBwH7cRRa3MJseE1Vj5xhYutxeHNotE/edit#gid=0).
