### ISSUE TITLE
Reviewing The Latest Version of VBET

### ISSUE THREAD

**Issue by shelbysawyer** [Riverscapes/riverscapes-tools#584]
The newest VBET projects, which 1) use the updated transform functions, 2) use the updated level path approach, and 3) have points for moving window analysis, are being run now on the [staging server](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch). I have some questions about this newest run, which will live here for now and can be discussed at our next meeting.

**1. Problem: ArcRAVE Shape Integrity Error**
- [ ] The [ArcRAVE shape integrity error](https://github.com/Riverscapes/riverscapes-tools/issues/527) is still present in multiple layers. When a VBET project is opened in ArcRAVE, only some parts of vector layers are visible. For example, only a few segments of valley bottom extent for a HUC 8 are visible. This is not an issue in QGIS. More details and pictures of this problem are listed in the official issue linked above.

**2. Potential problem: Likelihood of Valley Bottom Raster Bug**
- [x] The [Likelihood of Valley Bottom raster seems to be having more problems](https://github.com/Riverscapes/riverscapes-tools/issues/585) than what can be caused through symbology alone. When I look at the pixel values of the raster, there are many with "No Data" that are within the valley bottom. As the project is creating a valley bottom extent vector that looks good, this is probably just something in the display that I need to understand more. I will provide more detail in a linked issue.

**3. Question: Are valley bottom segments displaying expected metric values?**
- [x] Do we get reasonable numbers from valley bottom segments? Example: What is the proportion of active vs inactive valley bottom across perennial, intermittent, and ephemeral channels? Right now, valley bottom segments store the information for the WINDOW, not the segment. This is misleading and presents a problem for symbology. Tracking this [here](https://github.com/Riverscapes/riverscapes-tools/issues/600).

**4. Problem: File Names and Business Logic updates need to be made**
- [x] File names and project tree need to be updated to better align with the newest version of VBET. This issue is being tracked [here](https://github.com/Riverscapes/RiverscapesXML/issues/474). An inventory of VBET layers, project tree, etc can be found [here](https://docs.google.com/spreadsheets/d/17UrLA-ECxWLh4V6sT2qltDanEDvqw9hdKAb4HbbuHqE/edit#gid=1647925689).

**Comment by joewheaton** [comment]
These are helpful comments and questions @shelbysawyer... if you don't mention or assign anyone, I don't think it will get much attention. @philipbaileynar and @KellyMWhitehead lets schedule a time next week and get these sorted out.

**Comment by joewheaton** [comment]
> The newest VBET projects, which 1) use the updated transform functions, 2) use the updated level path approach, and 3) have points for moving window analysis, are being run now on the [staging server](https://northarrowresearchlabs.github.io/riverscapes-staging/#/Anabranch). I have some questions about this newest run, which will live here for now and can be discussed at our next meeting.
> 

Did they get discussed in a meeting @shelbysawyer? If so, please report here. 
> 1. Problem: The [ArcRAVE shape integrity error](https://github.com/Riverscapes/riverscapes-tools/issues/527) is still present in multiple layers. When a VBET project is opened in ArcRAVE, only some parts of vector layers are visible. For example, only a few segments of valley bottom extent for a HUC 8 are visible. This is not an issue in QGIS. More details and pictures of this problem are listed in the official issue linked above.

This is a problem, and one we'll need to get to the bottom of, but it is not the highest priority in my view.

> 2. Potential problem: The [Likelihood of Valley Bottom raster seems to be having more problems](https://github.com/Riverscapes/riverscapes-tools/issues/585) than what can be caused through symbology alone. When I look at the pixel values of the raster, there are many with "No Data" that are within the valley bottom. As the project is creating a valley bottom extent vector that looks good, this is probably just something in the display that I need to understand more. I will provide more detail in a linked issue.


> 3. Question: Proportion of active vs inactive valley bottom between perennial, intermittent, and ephemeral channels? Will document this in linked gist.

Have you done this?

> 4. Question: Why are there transform zone rasters for each LOE?

Do you mean these:
![image](https://user-images.githubusercontent.com/9723905/190856495-0fc4a149-81d9-4f8c-b141-9f97969431f0.png)

If so, they are not actually rasters... have you opened one? They are the transform functions:
![image](https://user-images.githubusercontent.com/9723905/190856576-f3e53673-818f-4143-980a-2712ff426263.png)

**Comment by shelbysawyer** [comment]
**Did they [initial questions posed] get discussed in a meeting @shelbysawyer? If so, please report here.**
> 
> > 1. Problem: The [ArcRAVE shape integrity error](https://github.com/Riverscapes/riverscapes-tools/issues/527) is still present in multiple layers. When a VBET project is opened in ArcRAVE, only some parts of vector layers are visible. For example, only a few segments of valley bottom extent for a HUC 8 are visible. This is not an issue in QGIS. More details and pictures of this problem are listed in the official issue linked above.
> 
**A: Yes, briefly discussed and was told that this is not a priority right now.**
> 
> > 2. Potential problem: The [Likelihood of Valley Bottom raster seems to be having more problems](https://github.com/Riverscapes/riverscapes-tools/issues/585) than what can be caused through symbology alone. When I look at the pixel values of the raster, there are many with "No Data" that are within the valley bottom. As the project is creating a valley bottom extent vector that looks good, this is probably just something in the display that I need to understand more. I will provide more detail in a linked issue.

**A: Not addressed in meeting, tracking in issue.**
> 
> > 3. Question: Proportion of active vs inactive valley bottom between perennial, intermittent, and ephemeral channels? Will document this in linked gist.
> 
**A: I ran into issues trying to do this (things weren't adding up, proportions didn't add up to 1, etc.), which spurred the conversation of points giving calculations for windows instead of segments. Will get back to this on Monday, 9/19.**
> 
> > 4. Question: Why are there transform zone rasters for each LOE?
> 
> Do you mean these: ![image](https://user-images.githubusercontent.com/9723905/190856495-0fc4a149-81d9-4f8c-b141-9f97969431f0.png)
> 
> If so, they are not actually rasters... have you opened one? They are the transform functions.

**A: @joewheaton I have seen and opened the PNG files that are used in the report, but I am talking about the individual rasters, currently housed in the intermediates folder. They look like this when added to a project:**

<img width="1174" alt="slope_transform_zones tif" src="https://user-images.githubusercontent.com/73311751/191054014-ab0e48f0-a63a-4a5c-b1d6-ad9aba621ac6.PNG">

Specifically, they are named:
```
slope_transform_zones.tif
hand_transform_zones.tif
twi_transform_zones.tif
```

I understand that they are a processing step, I just hadn't noticed them before and was (am) seeking clarification on them. After exposing all parts of the project with the `VBET_ALL.xml` file, I realized that these are probably just the normalized evidence layers. Is that right @KellyMWhitehead? One thing that I am still confused about is the value range for these rasters. For HAND, the range is 0 to 1 (what we'd expect for a normalized evidence raster), but for slope and TWI, the range is 0 to 2. What's causing that?

Here's a picture of those layers opened in Q:

<img width="920" alt="norm_evidence_rasters" src="https://user-images.githubusercontent.com/73311751/191056214-bf57c0a4-bab8-4ae0-b85a-919d4831f545.PNG">

**Comment by MattReimer** [comment]
@shelbysawyer can you review the VBET projects we've put up here:

https://github.com/Riverscapes/riverscapes-tools/discussions/637

Let's close this ticket or make some actionable checklists to get it closed

**Comment by shelbysawyer** [comment]
The remaining tasks for this issue are being tracked in other open (linked above) issues. Closing.
