### ISSUE TITLE
Flow Line Attribution

### ISSUE THREAD

**Issue by philipbaileynar** [Riverscapes/riverscapes-tools#834]
# Goal
Enrich the main flow line output feature classes with attributes that we know our downstream models either need for processing or for symbology.

Note that the goal is to do this in such a way as to make the Riverscapes Context project (i.e. data) as generic as possible so other jurisdictions can use the patterns. The actual RSC code can be bespoke because it will never get run for these other jurisdictions.

# Task

- [x] Enhance segmentation of output flow lines (all three segmentation distances 100, 300, 500) in the hydro derivatives to be segmented and attributed with the following:

Feature Class | Output Field name | Example
---|---|---
Ecoregions IV | `ecoregion_iv` | 'Ponderosa Pine Highlands'
Ownership | `ownership`|'BLM', 'DoD'
US State| `us_state`| 'MD', 'UT'

- [x] Ensure `FCode` is an attribute
- [x] Ensure TotDASQKM is an attribute*
- [x] Ensure LevelPath is an attribute (My preference is to rename it `level_path`
- [ ] Write layer metadata that identifies any field that needs to be rippled down through the system. My thinking here is to use a prefix `attribute_` or `key_attribute_` that can be interpreted by other code.

```xml
<Metadata>
    <Meta name="attribute_ecoregion">ecoregion_iv</Meta>
    <Meta name="attribute_ownership">ownership</Meta>
    <Meta name="attribute_us_state">us_state</Meta>
    <Meta name="attribute_fcode">fcode</Meta>
    <Meta name="attribute_totdasqkm">totdasqkm</Meta>
</Metadata>
```

# TotDASqKm

We discussed using SI units (i.e. metres), but drainage areas can get very big. I think we might want to use SQ KM for drainage area. This is consistent with NHD and avoids massive floating point values at the mouth of big rivers. NHD chose these units for a reason...

**Comment by philipbaileynar** [comment]
@philipbaileynar check that the attributes exist. Close if true.
